# Installing Docker and Docker Compose
---
- name: Installing Docker and Docker Compose
  hosts: all
  remote_user: pi
  become: true
  gather_facts: True

  tasks:
    - name: Update apt packages
      apt:
        update_cache: "yes"
        force_apt_get: "yes"

    - name: Install packages needed for Docker
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        force_apt_get: "yes"

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable"
        state: present
        mode: 0666

    - name: Update apt packages
      apt:
        update_cache: "yes"
        force_apt_get: "yes"

    - name: Install Docker and components
      apt:
        name: 
          - "docker-ce"
          - "docker-ce-cli"
          - "containerd.io"
        state: present
        force_apt_get: "yes"

    - name: Create docker group
      group:
        name: "docker"
        state: present

    - name: Adding user {{ ansible_ssh_user }} to docker group
      user:
        name: "{{ ansible_ssh_user }}"
        groups: "docker"
        append: "yes"
      
    # ==========================================

    - name: Install Docker and components
      apt:
        name: 
          - libffi-dev 
          - libssl-dev
          - python3-dev
          - python3
          - python3-pip
        state: present
        force_apt_get: "yes"
      tags: docker-compose-packages
      
    - name: Install Docker-Compose
      pip:
        name: docker-compose
        executable: pip3
      tags: docker-compose

    # ==========================================

    - name: Reboot server in order for changes to take place
      shell: "sleep 1 && reboot"
      async: 1
      poll: 0


